name: Build & Release Electron App

on:
  push:
    tags:
      - '*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Electron app
        run: |
          npm run build

      - name: Build Windows installer
        run: |
          npm run release -- --win --x64

      - name: Upload Windows installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
